// This file is generated by ./make.dart

class Build {
  static const String name = "GPTBox";
  static const int build = 149;
  static const String engine = "3.19.6";
  static const String buildAt = "2024-05-08 23:02:36";
  static const int modifications = 3;
}
