// This file is generated by ./make.dart

class BuildData {
  static const String name = "GPT";
  static const int build = 8;
  static const String engine = "3.16.6";
  static const String buildAt = "2024-01-12 18:17:27";
  static const int modifications = 24;
}
