// This file is generated by ./make.dart

class BuildData {
  static const String name = "GPT";
  static const int build = 6;
  static const String engine = "3.16.5";
  static const String buildAt = "2023-12-29 15:18:25";
  static const int modifications = 5;
}
