// This file is generated by ./make.dart

class Build {
  static const String name = "GPT";
  static const int build = 119;
  static const String engine = "3.19.2";
  static const String buildAt = "2024-03-05 16:56:19";
  static const int modifications = 2;
}
